### ISSUE TITLE
unable to pip install with Python 3.5

### ISSUE THREAD

**Issue by kamikaze** [cloudify-cosmo/cloudify-dsl-parser#112]
`
Collecting cloudify
  Using cached cloudify-3.4.tar.gz
Collecting cloudify-plugins-common==3.4 (from cloudify)
  Using cached cloudify-plugins-common-3.4.tar.gz
Collecting cloudify-rest-client==3.4 (from cloudify)
  Using cached cloudify-rest-client-3.4.tar.gz
Collecting cloudify-dsl-parser==3.4 (from cloudify)
  Using cached cloudify-dsl-parser-3.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\path\pycharm-packaging\cloudify-dsl-parser\setup.py", line 29
        except ImportError, e:
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
`

**Comment by kamikaze** [comment]
It is 2017, is there any chance that Cloudify finally will work with modern software? )

**Comment by mlittlej** [comment]
I'm having a similar issue, but I've been working through it on my forks (as of earlier today).

I've raised to following bug on Cloudify's Jira tracker (which they actually look at, as opposed to github). See: https://cloudifysource.atlassian.net/browse/CFY-6397

**Comment by nir0s** [comment]
Cloudify requires 2.7

**Comment by kamikaze** [comment]
@nir0s but Python 2.7 is very old and is supported by community until 2020. Who will want to start their projects with such a software that is going to be deprecated soon?
